### ISSUE TITLE
broken link to PPT

### ISSUE THREAD

**Issue by crazyideas21** [noise-lab/research-course#2]
On [the README](https://github.com/noise-lab/research-course/blob/master/README.md) page, there is a broken link to "understanding the goals of a Ph.D." (supposedly linked to https://github.com/noise-lab/research-course/blob/master/docs/slides/phy-why.ppt but `404`).

**Comment by feamster** [comment]
Thank you fixed in https://github.com/noise-lab/research-course/commit/c4cece15df1eb01f53a50ab2c3a271b671c3a5c1

**Comment by feamster** [comment]
Ah, linking PPT from github pages seems to be not straightforward. Will look into it.  All slides are available in the repo, meanwhile. I may need to use absolute links.

**Comment by feamster** [comment]
now fixed https://github.com/noise-lab/research-course/commit/3af463c85c75e6718b17ecd469cdf27fd574ed61
